MVC-proj/Models/SliderImage.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_proj.Models
{
    public class SliderImage
    {
        public int Id { get; set; }
        public string Image { get; set; }
        [NotMapped]
        public IFormFile File { get; set; }
        public Slider Slider { get; set; }
    }
}

MVC-proj/Areas/Admin/Controllers/SliderImageController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using MVC_proj.Areas.Admin.Constants;
using MVC_proj.Areas.Admin.Utilis;
using MVC_proj.Areas.Admin.ViewModels;
using MVC_proj.DAL;
using MVC_proj.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_proj.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SliderImageController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public SliderImageController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public async Task<IActionResult> Index()
        {
            var sliderImages = await _context.SliderImages.ToListAsync();
            return View(sliderImages);
        }

        //*** Create ***//

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SliderImage sliderImage)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }

            if (!sliderImage.File.IsSupported())
            {
                ModelState.AddModelError(nameof(sliderImage.File), "File is unsupproted");
                return View();
            }

            if (sliderImage.File.IsGreaterThanGivenSize(1024))
            {
                ModelState.AddModelError(nameof(SliderImage.File), "File size cannot be greater than 1 mb");
                return View();
            }

            sliderImage.Image = FileUtil.CreatedFile(FileConstants.ImagePath, sliderImage.File);

            await _context.SliderImages.AddAsync(sliderImage);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        //*** CreateMultipleFiles ***//

        public IActionResult CreateMultiple()
        {
            return View();
        }

        [HttpPost]
        [ActionName("CreateMultiple")]
        public async Task<IActionResult> CreateMultipleSliderImage(SliderImageCreateViewModel sliderImages)
        {
            foreach (var file in sliderImages.Files)
            {
                if(!ModelState.IsValid)
                {
                    return View();
                }
                if(!file.IsSupported())
                {
                    ModelState.AddModelError("File", $"{file.FileName} file is unsupported");
                    return View();
                }
                if(file.IsGreaterThanGivenSize(1024))
                {
                    ModelState.AddModelError(nameof(SliderImageCreateViewModel.Files), 
                        $"{file.FileName} File size is {file.Length}");
                    return View();
                }

                SliderImage sliderImage = new SliderImage();
                sliderImage.Image = FileUtil.CreatedFile(FileConstants.ImagePath, file);
                await _context.SliderImages.AddAsync(sliderImage);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //*** Delete ***//

        public async Task<IActionResult> Delete(int id)
        {
            SliderImage sliderImage = await _context.SliderImages.FindAsync(id);
            if (sliderImage == null)
            {
                return NotFound();
            }
            return View(sliderImage);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteSliderImage(int id)
        {
            SliderImage sliderImage = await _context.SliderImages.FindAsync(id);
            if (sliderImage == null)
            {
                return NotFound();
            }
            string path = Path.Combine(FileConstants.ImagePath, sliderImage.Image);
            FileUtil.DeleteFile(path);

            _context.SliderImages.Remove(sliderImage);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        
    }
}

MVC-proj/Areas/Admin/Views/SliderImage/Create.cshtml
@model SliderImage
@{
    ViewData["Title"] = "Create";
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Create New Slider Image</h4>
                    <form enctype="multipart/form-data" class="forms-sample" method="post" asp-controller="SliderImage" asp-action="Create">
                        <div class="form-group">
                            <label asp-for="File">Image</label>
                            <input class="form-control" asp-for="File" placeholder="Image" accept="image/*">
                            <span class="text-danger" asp-validation-for="File"></span>
                        </div>
                        <button type="submit" class="btn btn-primary me-2">Submit</button>
                        <button class="btn btn-light">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidatePartial" />
    <script src="https://cdn.ckeditor.com/ckeditor5/30.0.0/classic/ckeditor.js"></script>
}

MVC-proj/Areas/Admin/Views/SliderImage/CreateMultiple.cshtml
@model SliderImageCreateViewModel
@{
    ViewData["Title"] = "CreateMultiple";
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Create New Slider Image</h4>
                    <form enctype="multipart/form-data" class="forms-sample" method="post" asp-controller="SliderImage" asp-action="CreateMultiple">
                        <div class="form-group">
                            <label asp-for="Files">Image</label>
                            <input class="form-control" asp-for="Files" placeholder="Image" accept="image/*">
                            <span class="text-danger" asp-validation-for="Files"></span>
                        </div>
                        <button type="submit" class="btn btn-primary me-2">Submit</button>
                        <button class="btn btn-light">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

MVC-proj/Areas/Admin/Views/SliderImage/Delete.cshtml
@model SliderImage 
@{
    ViewData["Title"] = "Delete";
}

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
               <img src="~/img/@Model.Image" style="width:300px;height:300px;" />
                <p class="text-danger">Silmek istediyinizden eminsiniz mi ?</p>
                <a class="btn btn-secondary" asp-action="Index">Cancel</a>
                <form method="post" asp-action="Delete">
                    <button class="btn btn-danger" type="submit">Sil</button>
                </form>
            </div>
        </div>
    </div>
</div>

MVC-proj/Areas/Admin/Views/SliderImage/Index.cshtml
@model List<SliderImage>
@{
    ViewData["Title"] = "Index";
    int order = 0;
}

<div class="content-wrapper">
    <div class="row">
        <a class="btn btn-primary btn-lg" asp-action="CreateMultiple">Add Multiple Images</a>
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Basic Table</h4>
                    <p class="card-description">
                        Add class <code>.table</code>
                    </p>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Order</th>
                                    <th>Image</th>
                                    <th>Operations</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    order++;
                                    <tr>
                                        <td>@order</td>
                                        <td><img src="~/img/@item.Image" style="width:200px; height:200px; border-radius:50%; object-fit:cover;"/></td>
                                        <td>
                                            <a class="btn btn-primary" asp-controller="SliderImage" asp-action="Detail" asp-route-id="@item.Id">Detail</a>
                                            <a class="btn btn-warning" asp-controller="SliderImage" asp-action="Update" asp-route-id="@item.Id">Update</a>
                                            <a class="btn btn-danger" asp-controller="SliderImage" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MVC-proj/Areas/Admin/Views/SliderImage/Update.cshtml
@model SliderImage
@{
    ViewData["Title"] = "Update";
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Update New Slider Image</h4>
                    <form enctype="multipart/form-data" class="forms-sample" method="post" asp-controller="SliderImage" asp-action="Create">
                        <div class="form-group">
                            <label asp-for="File">Image</label>
                            <input class="form-control" asp-for="File" placeholder="Image" accept="image/*">
                            <span class="text-danger" asp-validation-for="File"></span>
                        </div>
                        <button type="submit" class="btn btn-primary me-2">Submit</button>
                        <button class="btn btn-light">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>