MVC-proj/Models/Layout.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_proj.Models
{
    public class Layout
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(70)]
        public string LinkedinUrl { get; set; }
        [Column("linkedin")]
        public string LinkedinTitle { get; set; }
        public string FacebookUrl { get; set; }
        public string FacebookTitle { get; set; }
        [MaxLength(50)]
        public string Description { get; set; }
        public string Image { get; set; }
        [NotMapped]
        public IFormFile File { get; set; }
    }
}

MVC-proj/Areas/Admin/Controllers/LayoutController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_proj.DAL;
using MVC_proj.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_proj.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class LayoutController : Controller
    {

        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public LayoutController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public async Task<IActionResult> Index()
        {
            var layouts = await _context.Layouts.ToListAsync();
            return View(layouts);
        }

        public async Task<IActionResult> Detail(int id)
        {
            var layout = await _context.Layouts.FindAsync(id);
            if(layout == null)
            {
                return NotFound();
            }

            return View(layout);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Layout layout)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }

            
            if (!layout.File.ContentType.Contains("image"))
            {
                ModelState.AddModelError(nameof(Layout.File), "File is unsupproted");
                return View();
            }

            if (layout.File.Length > 1024 * 1000)
            {
                ModelState.AddModelError(nameof(Layout.File), "File size cannot be greater than 1 mb");
                return View();
            }

            string fileName = Guid.NewGuid() + layout.File.FileName;
            string wwwRootPath = _env.WebRootPath;

            var path = Path.Combine(wwwRootPath, "img", fileName);
            FileStream stream = new FileStream(path, FileMode.Create);
            await layout.File.CopyToAsync(stream);
            stream.Close();

            layout.Image = fileName;

            await _context.Layouts.AddAsync(layout);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Delete(int id)
        {
            Layout layout = await _context.Layouts.FindAsync(id);
            if(layout == null)
            {
                return NotFound();
            }
            return View(layout);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteLayout(int id)
        {
            Layout layout = await _context.Layouts.FindAsync(id);
            if(layout == null)
            {
                return NotFound();
            }
            _context.Layouts.Remove(layout);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

MVC-proj/Areas/Admin/Views/Layout/Create.cshtml
@model Layout
@{
    ViewData["Title"] = "Create";
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Create New Layout</h4>
                    <form enctype="multipart/form-data" class="forms-sample" method="post" asp-controller="Layout" asp-action="Create">
                        <div class="form-group">
                            <label asp-for="LinkedinUrl">Linkedin URL</label>
                            <input class="form-control" asp-for="LinkedinUrl" placeholder="Linkedin URL">
                            <span class="text-danger" asp-validation-for="LinkedinUrl"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="LinkedinTitle">Linkedin Title</label>
                            <input class="form-control" asp-for="LinkedinTitle" placeholder="Linkedin Title">
                            <span class="text-danger" asp-validation-for="LinkedinTitle"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="FacebookUrl">Facebook URL</label>
                            <input class="form-control" asp-for="FacebookUrl" placeholder="Facebook URL">
                            <span class="text-danger" asp-validation-for="FacebookUrl"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="FacebookTitle">Facebook Title</label>
                            <input class="form-control" asp-for="FacebookTitle" placeholder="Facebook Title">
                            <span class="text-danger" asp-validation-for="FacebookTitle"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description">Description</label>
                            <textarea class="form-control" asp-for="Description" placeholder="Facebook Title"></textarea>
                            <span class="text-danger" asp-validation-for="Description"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="File">Image</label>
                            <input class="form-control" asp-for="File" placeholder="Image" accept="image/*">
                            <span class="text-danger" asp-validation-for="File"></span>
                        </div>
                        <button type="submit" class="btn btn-primary me-2">Submit</button>
                        <button class="btn btn-light">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
<partial name="_ValidatePartial"/>
    <script src="https://cdn.ckeditor.com/ckeditor5/30.0.0/classic/ckeditor.js"></script>
    <script src="https://ckeditor.com/docs/ckeditor5/latest/builds/guides/quick-start.html"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#Description'))
            .then(editor => {
                console.log(editor);
            })
            .catch(error => {
                console.error(error);
            });
    </script>
}

MVC-proj/Areas/Admin/Views/Layout/Delete.cshtml
@model Layout
@{
    ViewData["Title"] = "Delete";
}

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">@Model.Id</h4>
                <p class="card-description">

                </p>
                <p>
                    @Html.Raw(Model.Description)
                </p>
                <p class="text-danger">Silmek istediyinizden eminsiniz mi ?</p>
                <a class="btn btn-secondary" asp-action="Index">Cancel</a>
                <form method="post" asp-action="Delete">
                    <button class="btn btn-danger" type="submit">Sil</button>

                </form>
            </div>
        </div>
    </div>
</div>

MVC-proj/Areas/Admin/Views/Layout/Detail.cshtml
@model Layout
@{
    ViewData["Title"] = "Detail";
}

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Details:</h4>
                <p class="card-description">

                </p>
                <p> 
                    @Html.Raw(Model.Description) pages
                </p>
                <div>
                    <img src="~/img/@Model.Image" alt="image"  style="width:100px; height:100px; border-radius:50%; object-fit:cover;"/>
                </div>
            </div>
        </div>
    </div>
</div>

MVC-proj/Areas/Admin/Views/Layout/Index.cshtml
@model List<Layout>
@{
    ViewData["Title"] = "Index";
    int order = 0;
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Basic Table</h4>
                    <p class="card-description">
                        Add class <code>.table</code>
                    </p>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Order</th>
                                    <th>Facebook</th>
                                    <th>Facebook URL</th>
                                    <th>LinkedIn</th>
                                    <th>LinkedIn URL</th>
                                    <th>Operations</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    order++;
                                    <tr>
                                        <td>@order</td>
                                        <td>@item.LinkedinTitle</td>
                                        <td>@item.LinkedinUrl</td>
                                        <td>@item.FacebookTitle</td>
                                        <td>@item.FacebookUrl</td>
                                        <td>
                                            <a class="btn btn-primary" asp-controller="Layout" asp-action="Detail" asp-route-id="@item.Id">Detail</a>
                                            <a class="btn btn-warning">Update</a>
                                            <a class="btn btn-danger" asp-controller="Layout" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>